import { test } from "node:test";
import assert from "node:assert/strict";
import {
  GET as clientGET,
  MATRIX_CLIENT_DELEGATION,
} from "../../src/app/.well-known/matrix/client/route.ts";
import {
  GET as serverGET,
  MATRIX_SERVER_DELEGATION,
} from "../../src/app/.well-known/matrix/server/route.ts";

const APP_ORIGIN = "https://app.qwickword.com";

/*
  A Qwickword address is `@name:qwickword.com`, so every client asks this site
  where the messaging server is before it can do anything at all. If these two
  documents are wrong, absent or unparseable, the symptom is not "discovery
  failed" — it is a person being told their account does not exist.

  The same documents are generated by the messaging server's proxy in the
  platform repository. This application cannot import that generator, so the
  shapes are pinned literally below. These assertions are what will notice if
  the two ever drift apart.
*/

test("a client is told where the homeserver is, in the shape it expects", async () => {
  const response = clientGET();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^application\/json/);
  assert.deepEqual(await response.json(), {
    "m.homeserver": { base_url: "https://app.qwickword.com" },
    "m.identity_server": {},
  });
});

test("the call service is told the server's host and port", async () => {
  const response = serverGET();
  assert.equal(response.status, 200);
  assert.deepEqual(await response.json(), { "m.server": "app.qwickword.com:443" });
});

test("both documents are readable by a browser client that has no session yet", () => {
  // Without this header the fetch is blocked cross-origin and the client
  // reports only that the server could not be found.
  for (const response of [clientGET(), serverGET()]) {
    assert.equal(response.headers.get("access-control-allow-origin"), "*");
  }
});

test("the delegation points at the messaging host, never at this website", () => {
  // Pointing these at qwickword.com would send every client back here in a
  // loop, and this site speaks no messaging protocol.
  assert.equal(APP_ORIGIN, "https://app.qwickword.com");
  assert.equal(MATRIX_CLIENT_DELEGATION["m.homeserver"].base_url, APP_ORIGIN);
  assert.match(MATRIX_SERVER_DELEGATION["m.server"], /^app\.qwickword\.com:\d+$/u);
  assert.doesNotMatch(MATRIX_CLIENT_DELEGATION["m.homeserver"].base_url, /^https:\/\/qwickword\.com/u);
});

test("the homeserver is reached over https, because a session credential rides on it", () => {
  assert.match(MATRIX_CLIENT_DELEGATION["m.homeserver"].base_url, /^https:\/\//u);
});
